### PR TITLE
fixed some damage I did on nav-bar top & changed color of current_use…

### PR DESCRIPTION
**Pull request by Winkeltje84**
…r text to white

image

### CODE REVIEW

**Review by Dvessen83 — COMMENTED** [review]
Inline styling is not very pretty imo, 
maybe put something in the .scss file like:
.dropdown-toggle {
  color: white
}

**Comment by Winkeltje84** [comment]
staat nu in .scss

**Review by Dvessen83 — APPROVED** [review]
(y)

**Review by ewoudtm — APPROVED** [review]
lftm

**Pull request merged**
